"""Gzip web/index.html into HumidityController/webpage.h (a PROGMEM byte array).

Runs automatically as a PlatformIO pre-build script. Arduino IDE users run it by hand
after editing the page:   python tools/embed_web.py
"""
import gzip
import os
import sys

try:
    Import("env")  # noqa: F821  (only defined when run by PlatformIO/SCons)
    ROOT = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC = os.path.join(ROOT, "web", "index.html")
DST = os.path.join(ROOT, "HumidityController", "webpage.h")


def embed():
    if not os.path.exists(SRC):
        sys.exit(f"embed_web: {SRC} not found")
    with open(SRC, "rb") as f:
        raw = f.read()
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    lines = []
    for i in range(0, len(gz), 20):
        lines.append("  " + ",".join(f"0x{b:02x}" for b in gz[i:i + 20]) + ",")
    out = (
        "#pragma once\n"
        "// AUTO-GENERATED by tools/embed_web.py from web/index.html -- do not edit by hand.\n"
        f"// {len(raw)} bytes -> {len(gz)} bytes gzipped\n"
        "#include <Arduino.h>\n\n"
        f"const uint32_t INDEX_HTML_GZ_LEN = {len(gz)};\n"
        "const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n" + "\n".join(lines) + "\n};\n"
    )
    if os.path.exists(DST):
        with open(DST, "r", newline="\n") as f:
            if f.read() == out:
                return  # unchanged: leave it alone so the sketch isn't rebuilt
    with open(DST, "w", newline="\n") as f:
        f.write(out)
    print(f"embed_web: web/index.html {len(raw)} B -> webpage.h ({len(gz)} B gzipped)")


embed()
